#!/bin/bash

#Present user with options
#1. Search by Item ID
#2. Search by Media ID
#3. Search all done by today
#4. Search by title?
#5. Search by series?

echo "How do you want to search? Type 1 to search by Item ID, type 2 to search by Media ID, type 3 to see all digitizations done by today. Type Q if you want to stop searching. "
read search_option


#Query database for info
if [[ {$search_option} = "1" ]] ; then
	echo "Enter the Item ID number and press enter"
	read item_id_choice
	mysql -h ${host_name} -u ${user_name} -p${password} -D ${database} -e "USE ${database}; SELECT * from ${table_name3} WHERE item_id=${item_id_choice};"
elif [[ {$search_option} = "2" ]] ; then

elif [[ {$search_option} = "3" ]] ; then
elif [[ {$search_option} = "Q" || {$search_option} = "q" ]] ; then
exit 1
fi