#!/bin/bash

#get digibase_functions
SCRIPTDIR=$(dirname "${0}")
. "${SCRIPTDIR}/digibase_functions" || { echo "Missing '${SCRIPTDIR}/digibase_functions'. Exiting." ; exit 1 ;};

#Need to prompt user for item ID
echo "Type an item ID for an item you QCed and press enter"
read selected_item

#Now check to see if item exists

#Now ask if it passed, and write to the database
report -q -n "Did the video file for ${id} pass QC? (Y or N) "
read qc_answer

if [[ "${qc_answer}" = "y" ]] || [[ "${qc_answer}" = "Y" ]]; then
    mysql -h ${host_name} -u ${user_name} -p${password} -D ${database} -e "INSERT INTO ${table_name3} (qc_status), VALUES(passed qc)" 
    echo "QC status for ${selected_item}  changed to 'passed QC'."
fi

if [[ "${qc_answer}" = "n" ]] || [[ "${qc_answer}" = "N" ]]; then
    mysql -h ${host_name} -u ${user_name} -p${password} << EOF 
USE ${database};
INSERT INTO ${table_name3} (qc_status), VALUES(failed qc)
echo "QC status changed to ${selected_item} 'failed QC'."
fi

#Ask if they want to modify another file

#Loop back to beginning if they want to modify another file, or quit if they are done

UPDATE ${table_name3} SET digitization_status='digitized with errors' WHERE item_id=${id};

